package br.com.jogatina.ui.profile

import java.util.Locale

/** Pais (codigo ISO alpha-2 + nomes PT/EN). Gerado via umpirsky/country-list. */
data class Country(val code: String, val name: String, val nameEn: String)

/** Nome conforme o idioma do aparelho (PT ou EN). */
fun Country.displayName(): String =
    if (Locale.getDefault().language == "pt") name else nameEn

/** Bandeira em emoji a partir do codigo ISO (indicadores regionais). */
fun Country.flagEmoji(): String = flagEmoji(code)

/** Bandeira em emoji a partir do codigo ISO (indicadores regionais). */
fun flagEmoji(code: String): String = code.uppercase().map {
    Character.toString(0x1F1E6 + (it.code - 'A'.code))
}.joinToString("")

fun countryName(code: String?): String? =
    code?.let { c -> Countries.firstOrNull { it.code.equals(c, ignoreCase = true) }?.displayName() }

val Countries: List<Country> = listOf(
    Country("AF", "Afeganistão", "Afghanistan"),
    Country("AL", "Albânia", "Albania"),
    Country("DE", "Alemanha", "Germany"),
    Country("AD", "Andorra", "Andorra"),
    Country("AO", "Angola", "Angola"),
    Country("AI", "Anguila", "Anguilla"),
    Country("AQ", "Antártida", "Antarctica"),
    Country("AG", "Antígua e Barbuda", "Antigua & Barbuda"),
    Country("AR", "Argentina", "Argentina"),
    Country("DZ", "Argélia", "Algeria"),
    Country("AM", "Armênia", "Armenia"),
    Country("AW", "Aruba", "Aruba"),
    Country("SA", "Arábia Saudita", "Saudi Arabia"),
    Country("AU", "Austrália", "Australia"),
    Country("AZ", "Azerbaijão", "Azerbaijan"),
    Country("BS", "Bahamas", "Bahamas"),
    Country("BH", "Bahrein", "Bahrain"),
    Country("BD", "Bangladesh", "Bangladesh"),
    Country("BB", "Barbados", "Barbados"),
    Country("BZ", "Belize", "Belize"),
    Country("BJ", "Benin", "Benin"),
    Country("BM", "Bermudas", "Bermuda"),
    Country("BY", "Bielorrússia", "Belarus"),
    Country("BO", "Bolívia", "Bolivia"),
    Country("BW", "Botsuana", "Botswana"),
    Country("BR", "Brasil", "Brazil"),
    Country("BN", "Brunei", "Brunei"),
    Country("BG", "Bulgária", "Bulgaria"),
    Country("BF", "Burquina Faso", "Burkina Faso"),
    Country("BI", "Burundi", "Burundi"),
    Country("BT", "Butão", "Bhutan"),
    Country("BE", "Bélgica", "Belgium"),
    Country("BA", "Bósnia e Herzegovina", "Bosnia & Herzegovina"),
    Country("CV", "Cabo Verde", "Cape Verde"),
    Country("CM", "Camarões", "Cameroon"),
    Country("KH", "Camboja", "Cambodia"),
    Country("CA", "Canadá", "Canada"),
    Country("QA", "Catar", "Qatar"),
    Country("KZ", "Cazaquistão", "Kazakhstan"),
    Country("TD", "Chade", "Chad"),
    Country("CL", "Chile", "Chile"),
    Country("CN", "China", "China"),
    Country("CY", "Chipre", "Cyprus"),
    Country("VA", "Cidade do Vaticano", "Vatican City"),
    Country("CO", "Colômbia", "Colombia"),
    Country("KM", "Comores", "Comoros"),
    Country("CD", "Congo - Kinshasa", "Congo - Kinshasa"),
    Country("KP", "Coreia do Norte", "North Korea"),
    Country("KR", "Coreia do Sul", "South Korea"),
    Country("CR", "Costa Rica", "Costa Rica"),
    Country("CI", "Costa do Marfim", "Côte d’Ivoire"),
    Country("HR", "Croácia", "Croatia"),
    Country("CU", "Cuba", "Cuba"),
    Country("CW", "Curaçao", "Curaçao"),
    Country("DK", "Dinamarca", "Denmark"),
    Country("DJ", "Djibuti", "Djibouti"),
    Country("DM", "Dominica", "Dominica"),
    Country("EG", "Egito", "Egypt"),
    Country("SV", "El Salvador", "El Salvador"),
    Country("AE", "Emirados Árabes Unidos", "United Arab Emirates"),
    Country("EC", "Equador", "Ecuador"),
    Country("ER", "Eritreia", "Eritrea"),
    Country("SK", "Eslováquia", "Slovakia"),
    Country("SI", "Eslovênia", "Slovenia"),
    Country("ES", "Espanha", "Spain"),
    Country("SZ", "Essuatíni", "Eswatini"),
    Country("US", "Estados Unidos", "United States"),
    Country("EE", "Estônia", "Estonia"),
    Country("ET", "Etiópia", "Ethiopia"),
    Country("FJ", "Fiji", "Fiji"),
    Country("PH", "Filipinas", "Philippines"),
    Country("FI", "Finlândia", "Finland"),
    Country("FR", "França", "France"),
    Country("GA", "Gabão", "Gabon"),
    Country("GH", "Gana", "Ghana"),
    Country("GE", "Geórgia", "Georgia"),
    Country("GI", "Gibraltar", "Gibraltar"),
    Country("GD", "Granada", "Grenada"),
    Country("GL", "Groenlândia", "Greenland"),
    Country("GR", "Grécia", "Greece"),
    Country("GP", "Guadalupe", "Guadeloupe"),
    Country("GU", "Guam", "Guam"),
    Country("GT", "Guatemala", "Guatemala"),
    Country("GG", "Guernsey", "Guernsey"),
    Country("GY", "Guiana", "Guyana"),
    Country("GF", "Guiana Francesa", "French Guiana"),
    Country("GN", "Guiné", "Guinea"),
    Country("GQ", "Guiné Equatorial", "Equatorial Guinea"),
    Country("GW", "Guiné-Bissau", "Guinea-Bissau"),
    Country("GM", "Gâmbia", "Gambia"),
    Country("HT", "Haiti", "Haiti"),
    Country("HN", "Honduras", "Honduras"),
    Country("HK", "Hong Kong, RAE da China", "Hong Kong SAR China"),
    Country("HU", "Hungria", "Hungary"),
    Country("BV", "Ilha Bouvet", "Bouvet Island"),
    Country("CX", "Ilha Christmas", "Christmas Island"),
    Country("NF", "Ilha Norfolk", "Norfolk Island"),
    Country("IM", "Ilha de Man", "Isle of Man"),
    Country("AX", "Ilhas Aland", "Åland Islands"),
    Country("KY", "Ilhas Cayman", "Cayman Islands"),
    Country("CC", "Ilhas Cocos (Keeling)", "Cocos (Keeling) Islands"),
    Country("CK", "Ilhas Cook", "Cook Islands"),
    Country("FO", "Ilhas Faroe", "Faroe Islands"),
    Country("GS", "Ilhas Geórgia do Sul e Sandwich do Sul", "South Georgia & South Sandwich Islands"),
    Country("HM", "Ilhas Heard e McDonald", "Heard & McDonald Islands"),
    Country("FK", "Ilhas Malvinas", "Falkland Islands"),
    Country("MP", "Ilhas Marianas do Norte", "Northern Mariana Islands"),
    Country("MH", "Ilhas Marshall", "Marshall Islands"),
    Country("UM", "Ilhas Menores Distantes dos EUA", "U.S. Outlying Islands"),
    Country("PN", "Ilhas Pitcairn", "Pitcairn Islands"),
    Country("SB", "Ilhas Salomão", "Solomon Islands"),
    Country("TC", "Ilhas Turcas e Caicos", "Turks & Caicos Islands"),
    Country("VI", "Ilhas Virgens Americanas", "U.S. Virgin Islands"),
    Country("VG", "Ilhas Virgens Britânicas", "British Virgin Islands"),
    Country("ID", "Indonésia", "Indonesia"),
    Country("IQ", "Iraque", "Iraq"),
    Country("IE", "Irlanda", "Ireland"),
    Country("IR", "Irã", "Iran"),
    Country("IS", "Islândia", "Iceland"),
    Country("IL", "Israel", "Israel"),
    Country("IT", "Itália", "Italy"),
    Country("YE", "Iêmen", "Yemen"),
    Country("JM", "Jamaica", "Jamaica"),
    Country("JP", "Japão", "Japan"),
    Country("JE", "Jersey", "Jersey"),
    Country("JO", "Jordânia", "Jordan"),
    Country("KW", "Kuwait", "Kuwait"),
    Country("LA", "Laos", "Laos"),
    Country("LS", "Lesoto", "Lesotho"),
    Country("LV", "Letônia", "Latvia"),
    Country("LR", "Libéria", "Liberia"),
    Country("LI", "Liechtenstein", "Liechtenstein"),
    Country("LT", "Lituânia", "Lithuania"),
    Country("LU", "Luxemburgo", "Luxembourg"),
    Country("LB", "Líbano", "Lebanon"),
    Country("LY", "Líbia", "Libya"),
    Country("MO", "Macau, RAE da China", "Macao SAR China"),
    Country("MK", "Macedônia do Norte", "North Macedonia"),
    Country("MG", "Madagascar", "Madagascar"),
    Country("MW", "Malaui", "Malawi"),
    Country("MV", "Maldivas", "Maldives"),
    Country("ML", "Mali", "Mali"),
    Country("MT", "Malta", "Malta"),
    Country("MY", "Malásia", "Malaysia"),
    Country("MA", "Marrocos", "Morocco"),
    Country("MQ", "Martinica", "Martinique"),
    Country("MR", "Mauritânia", "Mauritania"),
    Country("MU", "Maurício", "Mauritius"),
    Country("YT", "Mayotte", "Mayotte"),
    Country("MM", "Mianmar (Birmânia)", "Myanmar (Burma)"),
    Country("FM", "Micronésia", "Micronesia"),
    Country("MD", "Moldova", "Moldova"),
    Country("MN", "Mongólia", "Mongolia"),
    Country("ME", "Montenegro", "Montenegro"),
    Country("MS", "Montserrat", "Montserrat"),
    Country("MZ", "Moçambique", "Mozambique"),
    Country("MX", "México", "Mexico"),
    Country("MC", "Mônaco", "Monaco"),
    Country("NA", "Namíbia", "Namibia"),
    Country("NR", "Nauru", "Nauru"),
    Country("NP", "Nepal", "Nepal"),
    Country("NI", "Nicarágua", "Nicaragua"),
    Country("NG", "Nigéria", "Nigeria"),
    Country("NU", "Niue", "Niue"),
    Country("NO", "Noruega", "Norway"),
    Country("NC", "Nova Caledônia", "New Caledonia"),
    Country("NZ", "Nova Zelândia", "New Zealand"),
    Country("NE", "Níger", "Niger"),
    Country("OM", "Omã", "Oman"),
    Country("PW", "Palau", "Palau"),
    Country("PA", "Panamá", "Panama"),
    Country("PG", "Papua-Nova Guiné", "Papua New Guinea"),
    Country("PK", "Paquistão", "Pakistan"),
    Country("PY", "Paraguai", "Paraguay"),
    Country("NL", "Países Baixos", "Netherlands"),
    Country("BQ", "Países Baixos Caribenhos", "Caribbean Netherlands"),
    Country("PE", "Peru", "Peru"),
    Country("PF", "Polinésia Francesa", "French Polynesia"),
    Country("PL", "Polônia", "Poland"),
    Country("PR", "Porto Rico", "Puerto Rico"),
    Country("PT", "Portugal", "Portugal"),
    Country("KG", "Quirguistão", "Kyrgyzstan"),
    Country("KI", "Quiribati", "Kiribati"),
    Country("KE", "Quênia", "Kenya"),
    Country("GB", "Reino Unido", "United Kingdom"),
    Country("CF", "República Centro-Africana", "Central African Republic"),
    Country("DO", "República Dominicana", "Dominican Republic"),
    Country("CG", "República do Congo", "Congo - Brazzaville"),
    Country("RE", "Reunião", "Réunion"),
    Country("RO", "Romênia", "Romania"),
    Country("RW", "Ruanda", "Rwanda"),
    Country("RU", "Rússia", "Russia"),
    Country("EH", "Saara Ocidental", "Western Sahara"),
    Country("WS", "Samoa", "Samoa"),
    Country("AS", "Samoa Americana", "American Samoa"),
    Country("SM", "San Marino", "San Marino"),
    Country("SH", "Santa Helena", "St. Helena"),
    Country("LC", "Santa Lúcia", "St. Lucia"),
    Country("SC", "Seicheles", "Seychelles"),
    Country("SN", "Senegal", "Senegal"),
    Country("SL", "Serra Leoa", "Sierra Leone"),
    Country("SG", "Singapura", "Singapore"),
    Country("SX", "Sint Maarten", "Sint Maarten"),
    Country("SO", "Somália", "Somalia"),
    Country("LK", "Sri Lanka", "Sri Lanka"),
    Country("SD", "Sudão", "Sudan"),
    Country("SS", "Sudão do Sul", "South Sudan"),
    Country("SR", "Suriname", "Suriname"),
    Country("SE", "Suécia", "Sweden"),
    Country("CH", "Suíça", "Switzerland"),
    Country("SJ", "Svalbard e Jan Mayen", "Svalbard & Jan Mayen"),
    Country("BL", "São Bartolomeu", "St. Barthélemy"),
    Country("KN", "São Cristóvão e Névis", "St. Kitts & Nevis"),
    Country("MF", "São Martinho", "St. Martin"),
    Country("PM", "São Pedro e Miquelão", "St. Pierre & Miquelon"),
    Country("ST", "São Tomé e Príncipe", "São Tomé & Príncipe"),
    Country("VC", "São Vicente e Granadinas", "St. Vincent & Grenadines"),
    Country("RS", "Sérvia", "Serbia"),
    Country("SY", "Síria", "Syria"),
    Country("TJ", "Tadjiquistão", "Tajikistan"),
    Country("TH", "Tailândia", "Thailand"),
    Country("TW", "Taiwan", "Taiwan"),
    Country("TZ", "Tanzânia", "Tanzania"),
    Country("CZ", "Tchéquia", "Czechia"),
    Country("IO", "Território Britânico do Oceano Índico", "British Indian Ocean Territory"),
    Country("TF", "Territórios Franceses do Sul", "French Southern Territories"),
    Country("PS", "Territórios palestinos", "Palestinian Territories"),
    Country("TL", "Timor-Leste", "Timor-Leste"),
    Country("TG", "Togo", "Togo"),
    Country("TK", "Tokelau", "Tokelau"),
    Country("TO", "Tonga", "Tonga"),
    Country("TT", "Trinidad e Tobago", "Trinidad & Tobago"),
    Country("TN", "Tunísia", "Tunisia"),
    Country("TM", "Turcomenistão", "Turkmenistan"),
    Country("TR", "Turquia", "Turkey"),
    Country("TV", "Tuvalu", "Tuvalu"),
    Country("UA", "Ucrânia", "Ukraine"),
    Country("UG", "Uganda", "Uganda"),
    Country("UY", "Uruguai", "Uruguay"),
    Country("UZ", "Uzbequistão", "Uzbekistan"),
    Country("VU", "Vanuatu", "Vanuatu"),
    Country("VE", "Venezuela", "Venezuela"),
    Country("VN", "Vietnã", "Vietnam"),
    Country("WF", "Wallis e Futuna", "Wallis & Futuna"),
    Country("ZW", "Zimbábue", "Zimbabwe"),
    Country("ZM", "Zâmbia", "Zambia"),
    Country("ZA", "África do Sul", "South Africa"),
    Country("AT", "Áustria", "Austria"),
    Country("IN", "Índia", "India"),
)
