package br.com.jogatina.ui.profile

/** Pais (codigo ISO alpha-2 + nome em portugues). Gerado via REST Countries. */
data class Country(val code: String, val name: String)

/** Bandeira em emoji a partir do codigo ISO (indicadores regionais). */
fun Country.flagEmoji(): String = code.uppercase().map {
    Character.toString(0x1F1E6 + (it.code - 'A'.code))
}.joinToString("")

fun countryName(code: String?): String? =
    code?.let { c -> Countries.firstOrNull { it.code.equals(c, ignoreCase = true) }?.name }

val Countries: List<Country> = listOf(
    Country("AF", "Afeganistão"),
    Country("AL", "Albânia"),
    Country("DE", "Alemanha"),
    Country("AD", "Andorra"),
    Country("AO", "Angola"),
    Country("AI", "Anguila"),
    Country("AQ", "Antártida"),
    Country("AG", "Antígua e Barbuda"),
    Country("AR", "Argentina"),
    Country("DZ", "Argélia"),
    Country("AM", "Armênia"),
    Country("AW", "Aruba"),
    Country("SA", "Arábia Saudita"),
    Country("AU", "Austrália"),
    Country("AZ", "Azerbaijão"),
    Country("BS", "Bahamas"),
    Country("BH", "Bahrein"),
    Country("BD", "Bangladesh"),
    Country("BB", "Barbados"),
    Country("BZ", "Belize"),
    Country("BJ", "Benin"),
    Country("BM", "Bermudas"),
    Country("BY", "Bielorrússia"),
    Country("BO", "Bolívia"),
    Country("BW", "Botsuana"),
    Country("BR", "Brasil"),
    Country("BN", "Brunei"),
    Country("BG", "Bulgária"),
    Country("BF", "Burquina Faso"),
    Country("BI", "Burundi"),
    Country("BT", "Butão"),
    Country("BE", "Bélgica"),
    Country("BA", "Bósnia e Herzegovina"),
    Country("CV", "Cabo Verde"),
    Country("CM", "Camarões"),
    Country("KH", "Camboja"),
    Country("CA", "Canadá"),
    Country("QA", "Catar"),
    Country("KZ", "Cazaquistão"),
    Country("TD", "Chade"),
    Country("CL", "Chile"),
    Country("CN", "China"),
    Country("CY", "Chipre"),
    Country("VA", "Cidade do Vaticano"),
    Country("CO", "Colômbia"),
    Country("KM", "Comores"),
    Country("CD", "Congo - Kinshasa"),
    Country("KP", "Coreia do Norte"),
    Country("KR", "Coreia do Sul"),
    Country("CR", "Costa Rica"),
    Country("CI", "Costa do Marfim"),
    Country("HR", "Croácia"),
    Country("CU", "Cuba"),
    Country("CW", "Curaçao"),
    Country("DK", "Dinamarca"),
    Country("DJ", "Djibuti"),
    Country("DM", "Dominica"),
    Country("EG", "Egito"),
    Country("SV", "El Salvador"),
    Country("AE", "Emirados Árabes Unidos"),
    Country("EC", "Equador"),
    Country("ER", "Eritreia"),
    Country("SK", "Eslováquia"),
    Country("SI", "Eslovênia"),
    Country("ES", "Espanha"),
    Country("SZ", "Essuatíni"),
    Country("US", "Estados Unidos"),
    Country("EE", "Estônia"),
    Country("ET", "Etiópia"),
    Country("FJ", "Fiji"),
    Country("PH", "Filipinas"),
    Country("FI", "Finlândia"),
    Country("FR", "França"),
    Country("GA", "Gabão"),
    Country("GH", "Gana"),
    Country("GE", "Geórgia"),
    Country("GI", "Gibraltar"),
    Country("GD", "Granada"),
    Country("GL", "Groenlândia"),
    Country("GR", "Grécia"),
    Country("GP", "Guadalupe"),
    Country("GU", "Guam"),
    Country("GT", "Guatemala"),
    Country("GG", "Guernsey"),
    Country("GY", "Guiana"),
    Country("GF", "Guiana Francesa"),
    Country("GN", "Guiné"),
    Country("GQ", "Guiné Equatorial"),
    Country("GW", "Guiné-Bissau"),
    Country("GM", "Gâmbia"),
    Country("HT", "Haiti"),
    Country("HN", "Honduras"),
    Country("HK", "Hong Kong, RAE da China"),
    Country("HU", "Hungria"),
    Country("BV", "Ilha Bouvet"),
    Country("CX", "Ilha Christmas"),
    Country("NF", "Ilha Norfolk"),
    Country("IM", "Ilha de Man"),
    Country("AX", "Ilhas Aland"),
    Country("KY", "Ilhas Cayman"),
    Country("CC", "Ilhas Cocos (Keeling)"),
    Country("CK", "Ilhas Cook"),
    Country("FO", "Ilhas Faroe"),
    Country("GS", "Ilhas Geórgia do Sul e Sandwich do Sul"),
    Country("HM", "Ilhas Heard e McDonald"),
    Country("FK", "Ilhas Malvinas"),
    Country("MP", "Ilhas Marianas do Norte"),
    Country("MH", "Ilhas Marshall"),
    Country("UM", "Ilhas Menores Distantes dos EUA"),
    Country("PN", "Ilhas Pitcairn"),
    Country("SB", "Ilhas Salomão"),
    Country("TC", "Ilhas Turcas e Caicos"),
    Country("VI", "Ilhas Virgens Americanas"),
    Country("VG", "Ilhas Virgens Britânicas"),
    Country("ID", "Indonésia"),
    Country("IQ", "Iraque"),
    Country("IE", "Irlanda"),
    Country("IR", "Irã"),
    Country("IS", "Islândia"),
    Country("IL", "Israel"),
    Country("IT", "Itália"),
    Country("YE", "Iêmen"),
    Country("JM", "Jamaica"),
    Country("JP", "Japão"),
    Country("JE", "Jersey"),
    Country("JO", "Jordânia"),
    Country("KW", "Kuwait"),
    Country("LA", "Laos"),
    Country("LS", "Lesoto"),
    Country("LV", "Letônia"),
    Country("LR", "Libéria"),
    Country("LI", "Liechtenstein"),
    Country("LT", "Lituânia"),
    Country("LU", "Luxemburgo"),
    Country("LB", "Líbano"),
    Country("LY", "Líbia"),
    Country("MO", "Macau, RAE da China"),
    Country("MK", "Macedônia do Norte"),
    Country("MG", "Madagascar"),
    Country("MW", "Malaui"),
    Country("MV", "Maldivas"),
    Country("ML", "Mali"),
    Country("MT", "Malta"),
    Country("MY", "Malásia"),
    Country("MA", "Marrocos"),
    Country("MQ", "Martinica"),
    Country("MR", "Mauritânia"),
    Country("MU", "Maurício"),
    Country("YT", "Mayotte"),
    Country("MM", "Mianmar (Birmânia)"),
    Country("FM", "Micronésia"),
    Country("MD", "Moldova"),
    Country("MN", "Mongólia"),
    Country("ME", "Montenegro"),
    Country("MS", "Montserrat"),
    Country("MZ", "Moçambique"),
    Country("MX", "México"),
    Country("MC", "Mônaco"),
    Country("NA", "Namíbia"),
    Country("NR", "Nauru"),
    Country("NP", "Nepal"),
    Country("NI", "Nicarágua"),
    Country("NG", "Nigéria"),
    Country("NU", "Niue"),
    Country("NO", "Noruega"),
    Country("NC", "Nova Caledônia"),
    Country("NZ", "Nova Zelândia"),
    Country("NE", "Níger"),
    Country("OM", "Omã"),
    Country("PW", "Palau"),
    Country("PA", "Panamá"),
    Country("PG", "Papua-Nova Guiné"),
    Country("PK", "Paquistão"),
    Country("PY", "Paraguai"),
    Country("NL", "Países Baixos"),
    Country("BQ", "Países Baixos Caribenhos"),
    Country("PE", "Peru"),
    Country("PF", "Polinésia Francesa"),
    Country("PL", "Polônia"),
    Country("PR", "Porto Rico"),
    Country("PT", "Portugal"),
    Country("KG", "Quirguistão"),
    Country("KI", "Quiribati"),
    Country("KE", "Quênia"),
    Country("GB", "Reino Unido"),
    Country("CF", "República Centro-Africana"),
    Country("DO", "República Dominicana"),
    Country("CG", "República do Congo"),
    Country("RE", "Reunião"),
    Country("RO", "Romênia"),
    Country("RW", "Ruanda"),
    Country("RU", "Rússia"),
    Country("EH", "Saara Ocidental"),
    Country("WS", "Samoa"),
    Country("AS", "Samoa Americana"),
    Country("SM", "San Marino"),
    Country("SH", "Santa Helena"),
    Country("LC", "Santa Lúcia"),
    Country("SC", "Seicheles"),
    Country("SN", "Senegal"),
    Country("SL", "Serra Leoa"),
    Country("SG", "Singapura"),
    Country("SX", "Sint Maarten"),
    Country("SO", "Somália"),
    Country("LK", "Sri Lanka"),
    Country("SD", "Sudão"),
    Country("SS", "Sudão do Sul"),
    Country("SR", "Suriname"),
    Country("SE", "Suécia"),
    Country("CH", "Suíça"),
    Country("SJ", "Svalbard e Jan Mayen"),
    Country("BL", "São Bartolomeu"),
    Country("KN", "São Cristóvão e Névis"),
    Country("MF", "São Martinho"),
    Country("PM", "São Pedro e Miquelão"),
    Country("ST", "São Tomé e Príncipe"),
    Country("VC", "São Vicente e Granadinas"),
    Country("RS", "Sérvia"),
    Country("SY", "Síria"),
    Country("TJ", "Tadjiquistão"),
    Country("TH", "Tailândia"),
    Country("TW", "Taiwan"),
    Country("TZ", "Tanzânia"),
    Country("CZ", "Tchéquia"),
    Country("IO", "Território Britânico do Oceano Índico"),
    Country("TF", "Territórios Franceses do Sul"),
    Country("PS", "Territórios palestinos"),
    Country("TL", "Timor-Leste"),
    Country("TG", "Togo"),
    Country("TK", "Tokelau"),
    Country("TO", "Tonga"),
    Country("TT", "Trinidad e Tobago"),
    Country("TN", "Tunísia"),
    Country("TM", "Turcomenistão"),
    Country("TR", "Turquia"),
    Country("TV", "Tuvalu"),
    Country("UA", "Ucrânia"),
    Country("UG", "Uganda"),
    Country("UY", "Uruguai"),
    Country("UZ", "Uzbequistão"),
    Country("VU", "Vanuatu"),
    Country("VE", "Venezuela"),
    Country("VN", "Vietnã"),
    Country("WF", "Wallis e Futuna"),
    Country("ZW", "Zimbábue"),
    Country("ZM", "Zâmbia"),
    Country("ZA", "África do Sul"),
    Country("AT", "Áustria"),
    Country("IN", "Índia"),
)
